version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
      - "9000:9000"
    links:
      - pilot
      - filterchain  
  pilot:
    image: vsalaka/mg-control-plane:0.0.1
    volumes:  
      - ./resources/:/home/wso2/resources/
    ports:
      - "18000:18000" 
  filterchain:
    image: vsalaka/mg-filter-chain:0.0.1
    ports:
      - "8081:8081"         
  # zipkin:
  #   image: openzipkin/zipkin
  #   expose:
  #   - "9411"
  #   ports:
  #   - "9411:9411"
