name: Test Coverage Uploader

on:
  push:
    branches:
      - envoy-gw
  workflow_dispatch:
    branches:
      - envoy-gw
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Checkout envoy-gw
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Tests
      run: mvn clean install --file pom.xml
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: unit_tests
