name: PR Check - Integration Tests

on:
  push:
    branches: [choreo]
  pull_request:
    branches: [choreo]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Echo string
        run: |
          IS_VALID=true
          echo "isValid=$IS_VALID" >> $GITHUB_OUTPUT
          RESPONSE=$(curl -o response2.json -s -w "%{http_code}" 'https://sts.choreo.dev/api/am/publisher/v2/apis/validate-openapi?organizationId=1c632c6b-a713-4b7e-b9cc-553853e59590&returnContent=true')
          echo "status_code=$RESPONSE" >> $GITHUB_OUTPUT
          echo "isValid=$IS_VALID"
          
          if [[ $RESPONSE != "401" || $IS_VALID == "false" ]]; then
            echo "API definition validation failed"
            exit 1
          else
            echo "Validation passed"
          fi 
          
          if [[ "${{ needs.validate_oas.outputs.status_code }}" != "200" || "${{ needs.validate_oas.outputs.isValid }}" == "false" ]]; then
             echo "API definition validation failed"
             cat response.json | jq .
             exit 1
          else
             echo "Validation passed"
          fi 
